<?php

namespace App\modelos\reportes;

use Illuminate\Database\Eloquent\Model;

class reporte_calificacionesModel extends Model
{
    protected $table = 'reporte_calificacionestrabajadornom035';
	protected $fillable = [
		'proyecto_id',
		'TRABAJADOR_ID',
		'ACONTECIMIENTO_CALIFICACION',
		'RECUERDOS_CALIFICACION',
		'ESFUERZO_CALIFICACION',
		'AFECTACION_CALIFICACION',
		'GUIA1_CALIFICACION',
		'C_AMBIENTE_CALIFICACION',
		'D_CONDICIONES_CALIFICACION',
		'C_AMBIENTE_NIVEL',
		'D_CONDICIONES_NIVEL',
		'C_FACTORES_CALIFICACION',
		'D_CARGA_CALIFICACION',
		'D_FALTA_CALIFICACION',
		'C_FACTORES_NIVEL',
		'D_CARGA_NIVEL',
		'D_FALTA_NIVEL',
		'C_FALTA_CALIFICACION',
		'C_FALTA_NIVEL',
		'C_ORGANIZACION_CALIFICACION',
		'D_JORNADA_CALIFICACION',
		'D_INTERFERENCIA_CALIFICACION',
		'C_ORGANIZACION_NIVEL',
		'D_JORNADA_NIVEL',
		'D_INTERFERENCIA_NIVEL',
		'C_LIDERAZGO_CALIFICACION',
		'D_LIDERAZGO_CALIFICACION',
		'D_RELACIONES_CALIFICACION',
		'D_VIOLENCIA_CALIFICACION',
		'C_LIDERAZGO_NIVEL',
		'D_LIDERAZGO_NIVEL',
		'D_RELACIONES_NIVEL',
		'D_VIOLENCIA_NIVEL',
		'C_ENTORNO_CALIFICACION',
		'D_RECONOCIMIENTO_CALIFICACION',
		'D_INSUFICIENTE_CALIFICACION',
		'C_ENTORNO_NIVEL',
		'D_RECONOCIMIENTO_NIVEL',
		'D_INSUFICIENTE_NIVEL',
		'GLOBAL_CALIFICACION',
		'GLOBAL_NIVEL'
	];
}
